# Generated by Django 3.1.3 on 2020-11-11 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='автор комментария')),
                ('comment', models.CharField(max_length=200, verbose_name='текст комментария')),
                ('aticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainmenu.mainmenu')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
