# Generated by Django 3.1.2 on 2020-11-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mainmenu',
            options={},
        ),
    ]
